.\" -*- nroff -*-
.TH WINETRICKS 1 "January 2025" "Winetricks 20250102" "Wine Package Manager"
.SH NAME
winetricks \- manage virtual Windows environments using Wine
.SH SYNOPSIS
.BI "winetricks "
[options] [verb ... ]
.SH DESCRIPTION
.B winetricks
is an easy way to work around common problems in Wine.
.PP
It provides simple commands to
tweak Wine settings,
download and install missing Windows DLLs and fonts,
or install various applications with appropriate workarounds for the current version of Wine.
.PP
It can be used via GUI or command line.  The command-line mode is intended both for interactive use and as a building block in fancier Wine frontends and in automated regression testing.

.B winetricks
with no arguments displays a GUI using either Zenity or Kdialog.

.SH OPTIONS
.TP
.B
\-\-country=CC
Set country code to CC and don't detect your IP address
when retrying downloads
.TP
.B
\-f, \-\-force
Don't check whether packages were already installed
.TP
.B
\-\-gui
Show GUI diagnostics even when driven by the command-line interface
.TP
.B
\-\-gui=OPT
Set OPT to kdialog or zenity to override GUI engine
.TP
.B
\-\-isolate
Install each app or game in its own bottle
.TP
.B
\-\-self\-update
Update this application to the last version
.TP
.B
\-\-update\-rollback
Rollback the last self update
.TP
.B
\-\-no\-isolate
Don't install each app or game in its own bottle (default)
.TP
.B
\-\-no\-clean
Don't delete temp directories (useful during debugging)
.TP
.B
\-\-optin
Opt in to reporting which verbs you use to the Winetricks maintainers
.TP
.B
\-\-optout
Opt out of reporting which verbs you use to the Winetricks maintainers
.TP
.B
\-q, \-\-unattended
Don't ask any questions, just install automatically
.TP
.B
\-t, \-\-torify
Run downloads under torify, if available
.TP
.B
\-v, \-\-verbose
Echo all commands as they are executed
.TP
.B
\-\-verify
Run (automated) GUI tests for verbs, if available
.TP
.B
\-h, \-\-help
Display this message and exit
.TP
.B
\-V, \-\-version
Display version and exit

.SH COMMANDS
.TP
.B
apps list
list verbs in category 'applications'
.TP
.B
benchmarks list
list verbs in category 'benchmarks'
.TP
.B
dlls list
list verbs in category 'dlls'
.TP
.B
fonts list
list verbs in category 'fonts'
.TP
.B
settings list
list verbs in category 'settings'
.TP
.B
list
list categories
.TP
.B
list-cached
list cached-and-ready-to-install verbs
.TP
.B
list-download
list verbs which download automatically
.TP
.B
list-manual-download
list verbs which download with some help from the user
.TP
.B
list-installed
list already-installed verbs
.TP
.B
arch=32|64
create wineprefix with 32 or 64 bit, this option must be
given before prefix=foobar and will not work in case of
the default wineprefix.
.TP
.B
prefix=foobar
select WINEPREFIX=$HOME/.local/share/wineprefixes/foobar
.TP
.B
annihilate
Delete ALL DATA AND APPLICATIONS INSIDE THIS WINEPREFIX

.PP
.SH EXAMPLES

.TP
To see list of available packages to install:
winetricks list-download
.TP
To install a package:
winetricks 7zip

.SH ENVIRONMENT VARIABLES
Wine checks several environment variables on startup:
.TP
.I WINE, WINE_BIN
If set, this specifies which wine binary to use by default
.TP
.I WINESERVER
If set, this specifies which wineserver to use by default
.TP
.I WINEPREFIX
If set, this specifies the location of the default .wine directory ( usually
.IR $HOME/.wine
).
.TP
.I XDG_CACHE_HOME
If set, this is path to system's user data cache (default: $HOME/.cache)
.I W_CACHE
path to Winetricks' user data cache (default: $XDG_CACHE_HOME/winetricks}

.SH AUTHORS
Dan Kegel, Austin English, and many others.  For a complete list,
please see the "Copyright" section in the file 'winetricks'.

.SH COPYRIGHT
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
See <https://www.gnu.org/licenses/>.
.SH BUGS
.PP
Bugs may be reported at
.I https://github.com/Winetricks/winetricks/issues
.PP
.SH AVAILABILITY
The most recent version of
.B winetricks
can be downloaded from
.I https://github.com/Winetricks/winetricks/releases/latest
.PP
The latest snapshot of the code may be obtained via git; see
.I https://github.com/Winetricks/winetricks/
.PP
Documentation for Winetricks can be found at
.I https://github.com/Winetricks/winetricks/wiki
.PP
For further information about
.B winetricks
see
.I https://github.com/Winetricks/winetricks/

.SH "SEE ALSO"
.BR wine (1)
